"""add_chat_session_mode

Revision ID: 99e435007db3
Revises: 48bfd3dffadc
Create Date: 2026-04-14 11:34:00.114763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e435007db3'
down_revision: Union[str, None] = '48bfd3dffadc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'mode')
    # ### end Alembic commands ###
