"""initial_schema_15_tables

Revision ID: a380c6a3b8e1
Revises: 
Create Date: 2026-04-13 15:40:46.758344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a380c6a3b8e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_logs_trace_id'), 'audit_event_logs', ['trace_id'], unique=False)
    op.create_table('core_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=True),
    sa.Column('owner_team', sa.String(length=120), nullable=True),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_mock', sa.Boolean(), nullable=True),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('core_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orch_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=60), nullable=False),
    sa.Column('source_run_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_channel', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orch_task_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('target_agent_type', sa.String(length=60), nullable=False),
    sa.Column('input_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('requires_judgement', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_type')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=60), nullable=False),
    sa.Column('linked_user_id', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_table('agent_heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['core_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.String(length=120), nullable=True),
    sa.Column('session_key', sa.String(length=255), nullable=False),
    sa.Column('context_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['core_channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_table('orch_schedule_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cron_expr', sa.String(length=60), nullable=False),
    sa.Column('target_task_definition_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_task_definition_id'], ['orch_task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orch_task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_definition_id', sa.UUID(), nullable=False),
    sa.Column('initiator_type', sa.String(length=30), nullable=False),
    sa.Column('initiator_id', sa.String(length=120), nullable=True),
    sa.Column('source_channel', sa.String(length=30), nullable=True),
    sa.Column('target_agent_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['target_agent_id'], ['core_agents.id'], ),
    sa.ForeignKeyConstraint(['task_definition_id'], ['orch_task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orch_task_runs_trace_id'), 'orch_task_runs', ['trace_id'], unique=False)
    op.create_table('realty_spatial_capture_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('property_ref', sa.String(length=255), nullable=True),
    sa.Column('video_uri', sa.Text(), nullable=True),
    sa.Column('audio_uri', sa.Text(), nullable=True),
    sa.Column('model_3d_uri', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['core_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('a2a_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_agent_id', sa.UUID(), nullable=False),
    sa.Column('target_agent_id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('envelope_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['core_agents.id'], ),
    sa.ForeignKeyConstraint(['target_agent_id'], ['core_agents.id'], ),
    sa.ForeignKeyConstraint(['task_run_id'], ['orch_task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_a2a_messages_trace_id'), 'a2a_messages', ['trace_id'], unique=False)
    op.create_table('audit_judgement_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_run_id', sa.UUID(), nullable=False),
    sa.Column('rule_result', sa.String(length=30), nullable=True),
    sa.Column('model_result', sa.String(length=30), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_run_id'], ['orch_task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=60), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('related_task_run_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_task_run_id'], ['orch_task_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judgement_case_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['judgement_case_id'], ['audit_judgement_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_approval_requests')
    op.drop_table('telegram_actions')
    op.drop_table('audit_judgement_cases')
    op.drop_index(op.f('ix_a2a_messages_trace_id'), table_name='a2a_messages')
    op.drop_table('a2a_messages')
    op.drop_table('realty_spatial_capture_sessions')
    op.drop_index(op.f('ix_orch_task_runs_trace_id'), table_name='orch_task_runs')
    op.drop_table('orch_task_runs')
    op.drop_table('orch_schedule_rules')
    op.drop_table('core_sessions')
    op.drop_table('agent_heartbeats')
    op.drop_table('telegram_users')
    op.drop_table('orch_task_definitions')
    op.drop_table('orch_reports')
    op.drop_table('core_channels')
    op.drop_table('core_agents')
    op.drop_index(op.f('ix_audit_event_logs_trace_id'), table_name='audit_event_logs')
    op.drop_table('audit_event_logs')
    # ### end Alembic commands ###
