"""add_agent_registry_fields

Revision ID: aca8a5fb9224
Revises: a380c6a3b8e1
Create Date: 2026-04-13 17:09:38.697470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aca8a5fb9224'
down_revision: Union[str, None] = 'a380c6a3b8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('core_agents', sa.Column('supported_task_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('core_agents', sa.Column('supported_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('core_agents', sa.Column('priority_score', sa.Integer(), nullable=True))
    op.add_column('core_agents', sa.Column('reliability_score', sa.Float(), nullable=True))
    op.add_column('core_agents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('core_agents', 'description')
    op.drop_column('core_agents', 'reliability_score')
    op.drop_column('core_agents', 'priority_score')
    op.drop_column('core_agents', 'supported_channels')
    op.drop_column('core_agents', 'supported_task_types')
    # ### end Alembic commands ###
