/**
 * @triple-h/chatbot — public types
 *
 * The AgentConfig is what each consuming agent (VIP, Meeting, Asset,
 * Smart Helmet, Health, ...) provides to the Chatbot module. It tells
 * the module who the agent is, what it can answer, and where to call
 * for transcription / talk / actions.
 *
 * STABLE API CONTRACT (v1.x)
 * --------------------------
 * The interfaces in this file are stable within the 1.x major version.
 * Any breaking change is a major bump (2.0.0). See CHANGELOG.md for
 * the full contract.
 *
 * Marked `@stable` = guaranteed not to change in 1.x.
 * Marked `@experimental` = may change without major bump.
 */

export type Lang = "auto" | "en" | "ko";

/** A single thing the agent can DO when the user asks for it. */
export interface AgentIntent {
  /** Stable internal name, e.g. "open_reports", "stock_summary" */
  name: string;
  /** Human description used by the LLM classifier to pick this intent */
  description: string;
  /** Example phrases the user might say (for fuzzy + LLM matching) */
  examples: { en?: string[]; ko?: string[] };
  /** What happens when this intent fires */
  action: ActionDefinition;
  /** Default reply text per language (optional — backend may override) */
  reply?: { en?: string; ko?: string };
  /** If true, ask the user to confirm before executing (good for destructive actions) */
  requiresConfirmation?: boolean;
  /** Custom confirmation text per language */
  confirmText?: { en?: string; ko?: string };
}

/** All action types supported by the module. */
export type ActionDefinition =
  | {
      type: "navigate";
      to: string;
      external?: boolean;
      /** After navigation, find element containing this text and scroll-highlight it.
       *  Useful for "open the X agent" → /agents page + scroll to X's card. */
      highlight?: string;
    }
  | { type: "trigger"; endpoint: string; method?: "GET" | "POST" | "PUT" | "DELETE" }
  | { type: "data_query"; endpoint: string; method?: "GET" | "POST" }
  | { type: "speak_only" }
  | { type: "workflow"; steps: WorkflowStep[] }
  /**
   * UI command — chatbot asks the host app to perform a UI action.
   * The host app registers handlers via the <ChatbotOverlay commands={...} /> prop.
   * Examples: "close_sidebar", "go_back", "scroll_top", "refresh", "toggle_dark_mode".
   */
  | { type: "ui_command"; command: string; params?: Record<string, unknown> }
  /**
   * Arbitrary JavaScript generated by the LLM when no intent matches but the
   * user's request is clearly an action. ALWAYS shows a confirmation UI before
   * running — the user must approve the generated code. Runs in the host page
   * context with access to document/window — power = responsibility.
   */
  | { type: "script"; code: string; explanation?: string };

/** One step in a multi-step workflow. */
export interface WorkflowStep {
  /** Display name shown in the process log */
  label: { en?: string; ko?: string };
  /** What this step does — same shape as AgentIntent.action minus nested workflows */
  action:
    | { type: "navigate"; to: string }
    | { type: "trigger"; endpoint: string; method?: "GET" | "POST" | "PUT" | "DELETE" }
    | { type: "data_query"; endpoint: string; method?: "GET" | "POST" }
    | { type: "speak"; text: { en?: string; ko?: string } };
  /** If true, pause for user confirmation before this step executes */
  requiresConfirmation?: boolean;
  /** Optional: extract value from previous step's response, expose as variable */
  exposeAs?: string;
}

/** Process log entry — what the user sees while a workflow runs. */
export interface ProcessStep {
  icon: string;
  label: string;
  status: "pending" | "running" | "done" | "error" | "warn";
}

/**
 * Knowledge sources the chatbot can consult to ANSWER questions
 * (TALK pillar). The backend implements these as REST endpoints — the
 * module just passes the user query and the endpoint URL.
 */
export interface KnowledgeSource {
  /** Stable name, e.g. "asset_portfolio", "current_kospi" */
  name: string;
  /** What the agent knows from this source — natural English */
  description: string;
  /** Endpoint that returns a JSON snapshot of the knowledge */
  endpoint: string;
  /** Optional: refresh interval — Module caches between calls */
  refreshIntervalMs?: number;
}

/**
 * Static knowledge about the AGENT itself — not its data, but its STRUCTURE
 * and CAPABILITIES. Used to answer questions like:
 *   "What is the Twins menu?" / "Where is the reports page?" /
 *   "What does this agent do?" / "How do I add a twin?"
 *
 * The VIP chatbot knows about VIP's menus + features. The Asset chatbot
 * knows about Asset's. Each agent provides its own.
 */
export interface AgentKnowledgeBase {
  /** One-paragraph elevator pitch — used for "what is this agent?" */
  purpose?: string;
  /** Sidebar / navigation menu items — used for "where is X?" / "what is X menu?" */
  menus?: { name: string; path: string; description: string }[];
  /** Major features — used for "what can you do" / "how do I X?" */
  features?: { name: string; description: string; how_to?: string }[];
  /** Pre-canned Q&A pairs — fastest answer for common questions */
  faq?: { q: string; a: string }[];
  /** Free-form additional context — markdown OK; included in LLM prompt */
  context?: string;
}

/** Visual + voice personality */
export interface AgentIdentity {
  /** Display name shown in panel header */
  name: string;
  /** First-time greeting, per language */
  greeting: { en?: string; ko?: string };
  /** Wake phrases that activate hands-free mode */
  wakeWords: { en?: string[]; ko?: string[] };
  /** Tone for the LLM's voice — formal / friendly / safety / clinical */
  tone?: "formal" | "friendly" | "safety" | "clinical" | "casual";
  /** Optional preferred TTS voice name (browser-specific) */
  ttsVoice?: string;
}

export interface AgentTheme {
  /** Brand color — header gradient + active states */
  primaryColor?: string;
  /** Accent color — mic active glow */
  accentColor?: string;
  /** Border radius preset */
  radius?: "sharp" | "md" | "lg" | "xl";
  panelWidth?: number;
  panelHeight?: number;
  position?: "bottom-right" | "bottom-left" | "top-right" | "top-left";
  /** "auto" = follow OS, "light"/"dark" = forced */
  darkMode?: "auto" | "light" | "dark";
}

/**
 * @stable
 * Privacy controls — critical for agents that handle sensitive data
 * (Health: medical info, Asset: financial, Smart Helmet: location).
 *
 * Agents opt INTO logging by default; sensitive agents should set
 * `logQueries: false` and `logReplies: false` to prevent the
 * SELF-IMPROVE pillar from persisting raw text.
 */
export interface PrivacyConfig {
  /** Persist user queries to chatbot_interactions table. Default: true. */
  logQueries?: boolean;
  /** Persist assistant replies. Default: true. Health/finance: usually false. */
  logReplies?: boolean;
  /**
   * Regex patterns (applied case-insensitive). Any match in query OR reply is
   * replaced with "[REDACTED]" before persistence.
   *
   * Examples:
   *   - SSN:    `\\d{3}-\\d{2}-\\d{4}`
   *   - Email:  `[\\w.+-]+@[\\w-]+\\.[\\w.-]+`
   *   - Phone:  `\\d{3}[-.\\s]?\\d{3,4}[-.\\s]?\\d{4}`
   *   - Card:   `\\b(?:\\d[ -]*?){13,16}\\b`
   */
  redactPatterns?: string[];
  /**
   * Auto-delete chatbot_interactions rows older than this. Default: keep forever.
   * Health agent: 30 days. Asset: 365. VIP: indefinite is fine.
   */
  dropAfterDays?: number;
  /**
   * If true, the entire SELF-IMPROVE pipeline is disabled for this agent —
   * no logging, no auto-vocab, no FAQ caching. Use for the most sensitive
   * agents that can't tolerate any persistent state.
   */
  disableSelfImprove?: boolean;
}

/**
 * @experimental — added in v1.1.0
 * Wire format for streaming responses. Pick the one your backend speaks.
 *
 *  - "openai-stream": OpenAI-compatible chat completions SSE.
 *      Lines: `data: {"choices":[{"delta":{"content":"..."}}]}`
 *      End:   `data: [DONE]`
 *      Most LLM gateways (OpenAI, OpenClaw, vLLM) speak this natively.
 *
 *  - "sse": generic Server-Sent Events. Module reads `data:` lines as text.
 *      Each event's payload is appended to the running reply.
 *      Use when your backend emits plain text deltas without JSON wrapping.
 *
 *  - "json": custom protocol. Supply your own `tokenExtractor` to parse
 *      each line. Use for any non-standard wire format.
 */
export type StreamProtocol = "openai-stream" | "sse" | "json";

/**
 * @experimental — added in v1.1.0
 * Callbacks that fire as a streaming reply arrives.
 */
export interface StreamingTalkCallbacks {
  /** Fires for each token / delta. Append to the current assistant turn. */
  onToken: (delta: string) => void;
  /** Fires once the stream identifies an intent (optional, protocol-dependent). */
  onIntent?: (intent: string) => void;
  /** Fires when the stream ends. `final` carries any post-stream metadata
   *  (action, source, language, etc.) — text reply is what `onToken` already streamed. */
  onComplete: (final: TalkResponse) => void;
  /** Fires on network error or aborted stream. */
  onError: (err: Error) => void;
}

/**
 * @experimental — added in v1.1.0
 * Streaming wire-protocol configuration. When set on AgentConfig, the
 * chatbot prefers `askStreaming()` over the single-shot `ask()`.
 */
export interface StreamingConfig {
  /** Wire format. Default "openai-stream". */
  protocol: StreamProtocol;
  /** Override URL — defaults to `${apiBase}/chatbot/talk/stream`. */
  endpoint?: string;
  /**
   * Optional custom request body builder. Use when the backend's request
   * shape differs from the default (e.g. OpenAI chat completions wants
   * `{model, messages, stream:true}` instead of `{query, intents, ...}`).
   *
   * Receives the standard TalkRequest (with extras like agentId, subAgents,
   * privacy). Return whatever JSON your backend expects.
   */
  bodyBuilder?: (req: TalkRequest) => unknown;
  /**
   * Optional custom token extractor. Receives one line of the SSE stream
   * (already stripped of `data: ` prefix) and returns:
   *   - `delta`: text to append to the running reply
   *   - `intent`: identified intent (optional)
   *   - `done`: true when stream is complete
   *
   * Required when `protocol === "json"`. Ignored for the other protocols.
   */
  tokenExtractor?: (line: string) => { delta?: string; intent?: string; done?: boolean };
}

/**
 * @experimental — added in v1.1.0
 * One sub-agent in an orchestrator-style multi-agent platform.
 *
 * Use this when your "main" agent is itself an orchestrator that dispatches
 * to N domain agents (Asset Agent → portfolio / lease / legal / equity / ...).
 * The chatbot will include the registry in every TALK request so the backend
 * (or its LLM classifier) can pick the right sub-agent for the user's query.
 */
export interface SubAgent {
  /** Stable id, e.g. "lease-agent", "portfolio-orchestrator" */
  id: string;
  /** Human display name */
  name: string;
  /** What this sub-agent specializes in — used by the classifier to route */
  description: string;
  /** Optional keywords that strongly route to this sub-agent (fast-path) */
  routingHints?: string[];
}

/**
 * @experimental — added in v1.1.0
 * How the module picks `targetAgentId` for each TALK request.
 *
 *  - "passthrough" (default): no routing. All queries go to the default backend.
 *      Use when there is one orchestrator that dispatches internally.
 *  - "auto": LLM classifier on the backend picks the sub-agent. Module sends
 *      the registry inline so the backend has full context.
 *  - "explicit": user picks the sub-agent via a UI selector. (UI for this
 *      lands in v1.2 — for v1.1 this behaves like "auto".)
 */
export type SubAgentRouting = "passthrough" | "auto" | "explicit";

/**
 * @experimental — added in v1.2.0
 *
 * Voice / Calling Agent configuration. When set, the agent gains a full
 * phone-call surface: inbound AI receptionist, outbound calls (single +
 * batch campaigns), live transcript stream, and call history.
 *
 * Consumers mount the <VoiceDashboard /> from `@triple-h/chatbot/voice-ui`
 * passing this object — every per-agent setting (phone number, voice,
 * escalation target, working hours, pacing) is config-driven, so a second
 * agent (Real Estate, Health, ...) only needs to declare a new VoiceConfig.
 *
 * Backend resolves `agentId` (from AgentConfig) plus this block to know
 * which telephony assistant to dial, where to escalate urgent calls, and
 * which knowledge base feeds the in-call LLM.
 */
export interface VoiceConfig {
  /**
   * Provider name. Currently supported:
   *   - "selfhosted": Asterisk (SIP edge) + local Whisper + local LLM (Ollama)
   *     + local TTS (MeloTTS). Pay only carrier fees. Requires GPU server.
   *   - "elevenlabs": ElevenLabs Conversational AI (best Korean voice, $$/min).
   *   - "vapi":       Vapi (US-focused, $$/min).
   * "twilio" / "bird" / "nhn-toast" reserved for future direct integrations.
   *
   * Backend dispatch is in `apps/orchestrator-api/routers/voice.py`
   * (_dispatch_outbound) — keyed off this string via voice_provider_assistants.
   */
  provider: "selfhosted" | "elevenlabs" | "vapi" | "twilio" | "bird" | "nhn-toast";
  /**
   * Provider-side assistant identifier. For Vapi this is the assistant UUID
   * configured in the Vapi console; for Twilio this is a TwiML application SID.
   */
  assistantId: string;
  /**
   * The phone number that owns this agent's calls — E.164 format.
   * For Korean 070 numbers: "+82-70-XXXX-XXXX".
   * Inbound calls to this number ring the AI; outbound calls show this
   * number as caller-ID.
   */
  phoneNumber: string;
  /**
   * Default language for new calls when no caller-language hint is available.
   * The in-call LLM may switch mid-call based on what the caller speaks.
   */
  defaultLanguage: Lang;
  /**
   * Where urgent calls (urgency=high) get escalated to. Resolved by the
   * orchestrator's escalation pipeline on call.ended or mid-call when the
   * LLM raises urgency.
   */
  escalationChannel: VoiceEscalationChannel;
  /**
   * Catalog of preset outbound reasons available in the OutboundCallForm
   * and BatchCallCampaign. Real Estate's set differs from VIP's — that's
   * the whole point of config-driving this.
   */
  outboundReasons: VoiceOutboundReason[];
  /**
   * Batch campaign pacing — max outbound calls per hour the agent will dial
   * autonomously. Soft limit; carriers may impose their own.
   * Korean carriers typically allow 12–20 calls/hour from a single 070
   * before flagging spammy patterns. Default: 12.
   */
  batchPacing: number;
  /**
   * Hours during which outbound calls are allowed (24h, in the agent's
   * timezone). Inbound calls are always accepted. KR best practice:
   * 09:00–21:00.
   */
  workingHours: { start: number; end: number; timezone: string };
  /**
   * Recording-consent disclosure spoken (or text-displayed) as the first
   * sentence of every call. Required by Korean Communications Privacy Act
   * for call recording. Provide both languages; the assistant picks based
   * on the call's resolved language.
   */
  recordingDisclosure: { en?: string; ko?: string };
  /**
   * Hard per-recipient rate limit — same recipient can't be called by this
   * agent more than N times within `perRecipientWindowDays`. Default:
   * { maxCalls: 1, perRecipientWindowDays: 7 }.
   */
  perRecipientLimit?: { maxCalls: number; perRecipientWindowDays: number };
  /**
   * Where audio recordings are stored. Defaults to the backend's own
   * Supabase Storage bucket under `/{agentId}/{callId}.mp3` with 30-day
   * signed URLs.
   */
  recordingRetentionDays?: number;
  /**
   * Optional override — by default the dashboard fetches against
   * `${AgentConfig.apiBase}/api/voice/${agentId}/...`. Set this only if
   * voice endpoints live on a separate host.
   */
  apiBase?: string;
}

/**
 * @experimental — added in v1.2.0
 * Where an urgent call (urgency=high) gets escalated to.
 *
 * VIP routes to a Telegram bot that pings the boss; Real Estate may route
 * to a Slack channel; Health might route to an on-call PagerDuty rotation.
 * Adding new channels means adding a new branch here.
 */
export type VoiceEscalationChannel =
  | { kind: "telegram"; chatId: string; botEnvKey?: string }
  | { kind: "slack"; channel: string; botEnvKey?: string }
  | { kind: "email"; to: string }
  | { kind: "webhook"; url: string; method?: "POST" | "PUT" }
  | { kind: "none" };

/**
 * @experimental — added in v1.2.0
 * One preset outbound reason. The agent (or its operator) picks one when
 * placing a call; the LLM uses `scriptTemplate` as the seed for the
 * opening sentence. `{name}`, `{amount}`, `{dueDate}` placeholders are
 * filled from the recipient's `context` map.
 */
export interface VoiceOutboundReason {
  /** Stable id — used in the API + DB */
  id: string;
  /** Human label per language for UI dropdowns */
  label: { en?: string; ko?: string };
  /** Opening-line template per language — see placeholder notes above */
  scriptTemplate: { en?: string; ko?: string };
  /**
   * Optional: which `context` keys this reason expects (for UI validation
   * + CSV-import column mapping). E.g. ["amount","dueDate","lease"].
   */
  requiredContextKeys?: string[];
}

/**
 * Top-level config — what each agent provides to <ChatbotOverlay>.
 */
export interface AgentConfig {
  /** Stable agent identifier, e.g. "vip", "meeting", "asset", "helmet", "health" */
  agentId: string;
  /** Backend base URL for /chatbot/* endpoints */
  apiBase: string;

  identity: AgentIdentity;

  /** What the user can ask the chatbot to DO (action pillar) */
  intents: AgentIntent[];

  /** Live data sources (talk pillar — endpoints the backend queries) */
  knowledge: KnowledgeSource[];

  /** Static knowledge about this agent's UI + capabilities — used to answer
   *  "what is X menu?" / "where is Y?" / "what does this agent do?" */
  knowledgeBase?: AgentKnowledgeBase;

  /** Optional theme overrides */
  theme?: AgentTheme;

  /** Languages this agent supports — first one is default for "auto" */
  supportedLanguages?: Lang[];

  /** Optional auth header builder — called on every API request */
  authHeaders?: () => Record<string, string>;

  /** Privacy / redaction controls — default: log everything plain-text */
  privacy?: PrivacyConfig;

  /**
   * @experimental — added in v1.1.0
   * Streaming configuration. When set, the chatbot uses `askStreaming()`
   * (token-by-token rendering) instead of the single-shot `ask()`. Falls
   * back to single-shot if streaming is unset or the network fails.
   */
  streaming?: StreamingConfig;

  /**
   * @experimental — added in v1.1.0
   * Sub-agent registry for orchestrator-style platforms. If empty/unset,
   * the chatbot operates as a single-agent (default v1.0 behavior).
   */
  subAgents?: SubAgent[];

  /**
   * @experimental — added in v1.1.0
   * How the module routes queries across `subAgents`. Default "passthrough".
   */
  subAgentRouting?: SubAgentRouting;

  /**
   * @experimental — added in v1.2.0
   * Voice / Calling Agent configuration. When set, the agent gains a phone
   * presence — inbound AI receptionist + outbound calls — mounted via
   * <VoiceDashboard /> from `@triple-h/chatbot/voice-ui`.
   *
   * Agents without `voice` simply don't render the calls UI.
   */
  voice?: VoiceConfig;
}

// ---------------------------------------------------------------------------
// Talk responses — what the backend returns from POST /chatbot/talk
// ---------------------------------------------------------------------------

export interface ConversationTurn {
  role: "user" | "assistant";
  text: string;
  intent?: string;
  /** Path the user navigated to as a result, if any — for pronoun resolution */
  navigatedTo?: string;
}

export interface TalkRequest {
  query: string;          // user's natural-language question
  language: Lang;
  agentId: string;        // tells the backend which agent's context to use
  /** Recent conversation turns — used by the LLM to resolve "it", "that", "again" etc. */
  history?: ConversationTurn[];
  /** Current page path the user is viewing — extra context for the LLM */
  currentPath?: string;

  /**
   * @experimental — added in v1.1.0
   * Sub-agent registry, sent inline so backend classifier can route. Mirrors
   * AgentConfig.subAgents — module forwards it on each request.
   */
  subAgents?: SubAgent[];
  /**
   * @experimental — added in v1.1.0
   * Routing strategy hint for the backend. Mirrors AgentConfig.subAgentRouting.
   */
  subAgentRouting?: SubAgentRouting;
  /**
   * @experimental — added in v1.1.0
   * Pre-resolved sub-agent id. Set when routing is "explicit" (user picked)
   * or when the chatbot has already classified the target. Backend should
   * dispatch directly without re-classifying.
   */
  targetAgentId?: string;
}

export interface TalkResponse {
  /** Spoken / displayed reply (TTS-friendly, no markdown) */
  reply: string;
  /** Resolved language of reply */
  language: "en" | "ko";
  /** If the engine determined an intent, it's named here */
  intent?: string;
  /** If the engine resolves to an ACTION, frontend should execute it */
  action?: ActionDefinition;
  /** Spoken first while the action runs (e.g. "On it, Boss…") */
  ackReply?: string;
  /** Multi-step workflow plan when the LLM decomposes a compound request */
  steps?: ProcessStep[];
  /** True when the action needs explicit user confirmation before running */
  requiresConfirmation?: boolean;
  /** Confirmation prompt to show the user */
  confirmText?: string;
  /** For debugging — was this answered from keyword, llm, or knowledge? */
  source?: "keyword" | "llm" | "knowledge" | "fallback" | "workflow";
}
